### PR TITLE
Mention torcx will be less actively used

### LINKED ISSUE #123: Status of torcx in fedora/redhat coreos?
I built a bit of tooling to package things up for torcx. Is there any clarity yet on whether torcx has a place in coreos' future? I'd like to either polish that up and share, or switch to whatever the new OS will use for the purpose.

### PR DESCRIPTION
**Pull request by kamalmarhubi**
closes #123

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Happy to change wording, but I think a note to this effect in the readme would be useful.

**Comment by kamalmarhubi** [comment]
@lucab @squeed @bgilbert thoughts?

**Comment by kamalmarhubi** [comment]
One more ping, otherwise will close this out in about a week.

**Comment by lucab** [comment]
@kamalmarhubi sorry for the very late reply, I missed earlier pings. I'm in favor of closing this PR. In general we are not going to announce deprecation plans for every single component, but just the umbrella one for Container Linux (covering all projects custom built/maintained for it).

**Comment by kamalmarhubi** [comment]
Makes sense, thanks for the info!

**Pull request closed without merging**
